# Generated by Django 5.1.6 on 2025-02-07 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buddyTracker', '0002_alter_pet_breed_alter_pet_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='id',
            new_name='pet_id',
        ),
    ]
