# Generated by Django 4.2.23 on 2025-06-26 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buddyTracker', '0003_rename_id_pet_pet_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formoption',
            name='field_type',
            field=models.CharField(choices=[('CharField', 'Text'), ('DateField', 'Date'), ('FloatField', 'Decimal Number'), ('IntegerField', 'Integer Number'), ('ImageField', 'Image')], help_text='Select the data type for the field', max_length=50, verbose_name='Field Type'),
        ),
        migrations.CreateModel(
            name='TrackerEntryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='entry_images/')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='buddyTracker.trackerentries')),
            ],
        ),
    ]
